services:
  backend: 
    build:
      context: .
    image: yoaliofficial/traveller-demo-backend:latest
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ${GCP_CREDENTIALS}:/root/.config/gcloud:ro
    environment:
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=traveler-db
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres
    ports:
      - 35000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}